import Navbar from '../lib/components/navbar/Navbar'
import OSFrame from '../lib/components/OSFrame'
import Providers from '../lib/providers/Providers'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {

  return (
    <html lang="en">
       <head>
        <link rel="stylesheet" href="https://use.typekit.net/blx7ido.css"/>
		  </head>
      <body className='grid h-screen w-screen items-center'>
        {/*  box-border border-x-[5px] border-b-[5px] border-gray-300 bg-gray-300 */}
        <Providers>
          <OSFrame>
            <Navbar/>
              <div className='grid grid-cols-1 grid-rows-1 h-full w-full pt-[48px] '>
                {authModal}
                {children}
              </div>
          </OSFrame>
        </Providers>
      </body>
    </html>
  )
}
