import Navbar from '../lib/components/navbar/Navbar'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
       <head>
        <link rel="stylesheet" href="https://use.typekit.net/blx7ido.css"/>
		  </head>
      <body className='grid h-screen w-screen items-center box-border border-[5px] border-gray-300 bg-gray-300'>
        <Navbar/>
            <div className='pt-12 h-full'>
              {children}
            </div>
      </body>
    </html>
  )
}
