import Navbar from '@/lib/components/navbar'
import './globals.css'
import Scanlines from '@/lib/effects/VFX/Scanlines/Scanlines'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
       <head>
        <link rel="stylesheet" href="https://use.typekit.net/blx7ido.css"/>
		  </head>
      <body className='grid h-screen w-screen items-center box-border border-[5px] border-gray-300 bg-gray-300'>
        <Navbar/>
        {/* <div className='grid w-full h-full bg-yellow-100'>
          <div className='grid col-start-1 row-start-1'> */}
            {/* remembered I can't click through the scanlines layer */}
            {/* <div className='w-screen h-[62px]'></div>
            <Scanlines/> */}
            {children}
          {/* </div>
        </div> */}
      </body>
    </html>
  )
}
