import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  authModal,
}) {

  return (
    <html lang="en">
       <head>
        <link rel="stylesheet" href="https://use.typekit.net/blx7ido.css"/>
		  </head>
      <body className='grid h-screen w-screen items-center'>
          <div className='grid grid-cols-1 grid-rows-1 h-full w-full pt-[48px] '>
            {authModal}
            {children}
          </div>
      </body>
    </html>
  )
}
